# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bd977fb2e718a7ed24a9c056179dbeea903f077a73bfbdbc57e848ea0c30d44cd44ac17af0d32a9a5aff9716c4680b3f369769f4741953c8d8f368a9700e7f2

test:
  secret_key_base: 5932b7faf84b66be710bae7d83969efe1a3c02ec2e88f8ce5884cf0163dcf447622265c59825c791d44d1ceb5914b0184c19ce10d028764b6d8bea04f727155b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
